// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3qgRPRegwvBihiEZLLqceF9PNVLHr1YY',
    appId: '1:898549245670:web:325f9ce6543663270d3d27',
    messagingSenderId: '898549245670',
    projectId: 'my-expense-tracker-56bec',
    authDomain: 'my-expense-tracker-56bec.firebaseapp.com',
    storageBucket: 'my-expense-tracker-56bec.appspot.com',
    measurementId: 'G-YG9Z713TK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7YxtRZKgaIYMoprmYuhBTtvEHzOXMdo',
    appId: '1:898549245670:android:f0cfee7ea0c444190d3d27',
    messagingSenderId: '898549245670',
    projectId: 'my-expense-tracker-56bec',
    storageBucket: 'my-expense-tracker-56bec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY_LysQL9FeEoPOVz5-m9cxI0KFcSd5oE',
    appId: '1:898549245670:ios:f9aebee5680566580d3d27',
    messagingSenderId: '898549245670',
    projectId: 'my-expense-tracker-56bec',
    storageBucket: 'my-expense-tracker-56bec.appspot.com',
    iosBundleId: 'com.example.myExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY_LysQL9FeEoPOVz5-m9cxI0KFcSd5oE',
    appId: '1:898549245670:ios:f9aebee5680566580d3d27',
    messagingSenderId: '898549245670',
    projectId: 'my-expense-tracker-56bec',
    storageBucket: 'my-expense-tracker-56bec.appspot.com',
    iosBundleId: 'com.example.myExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3qgRPRegwvBihiEZLLqceF9PNVLHr1YY',
    appId: '1:898549245670:web:900f532e4c6eb84b0d3d27',
    messagingSenderId: '898549245670',
    projectId: 'my-expense-tracker-56bec',
    authDomain: 'my-expense-tracker-56bec.firebaseapp.com',
    storageBucket: 'my-expense-tracker-56bec.appspot.com',
    measurementId: 'G-LKWN98HT6P',
  );
}
